\input texinfo
@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2017 David Pirotte <david at altosw dot be>.
@c See the file guile-cv.texi for copying conditions.


Guile-CV uses a series of support modules, each documented in the
following subsections. You may either import them all, like this
@code{(use-modules (cv support))}, or individually, such as
@code{(use-modules (cv support modules))}, @code{(use-modules (cv
support goops))}, ...


@menu
* Modules::
* Goops::
* G-export::
* Utils::
@end menu


@include api-support-modules.texi


@node Goops
@subsection Goops

@node G-export
@subsection G-export

@node Utils
@subsection Utils

