\input texinfo
@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2017 David Pirotte <david at altosw dot be>.


@insertcopying


@c @node API Overview
@c @subsection API Overview


@subheading Guile-CV Low Level API

The Guile-CV low level API is ...


@subheading Guile-CV High Level API

Guile-CV will also provide a higher level API ...


@node Naming Conventions
@subsection Naming Conventions


@subheading Vigra Funtions

Guile-CV low level API procedure names hat bind a Vigra function
always start with @code{vigra-} ...

@example
bluefox
->
redbear
@end example


@include api-abreviations.texi
