@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2021 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


@node Modules
@subsection Modules


@indentedblock
@table @code
@item @ref{re-export-public-interface}
@end table
@end indentedblock


@anchor{re-export-public-interface}
@deffn Syntax re-export-public-interface mod1 mod2 ...

Re-export the public interface of a @var{mod1} @var{mod2} @dots{}

Invoked like @code{use-modules}, where each @var{mod1} @var{mod2}
@dots{} is a module name (a list of symbol(s)).
@end deffn
