@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2017 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


@node Filters
@subsection Filters

The Guile-CV procedures and methods to filter images.


@subheading Procedures

@ifhtml
@indentedblock
@table @code
@item @ref{im-gaussian-blur}
@item @ref{im-gaussian-blur-channel}
@item @ref{im-gaussian-gradient}
@item @ref{im-gaussian-gradient-channel}
@end table
@end indentedblock
@end ifhtml


@anchor{im-gaussian-blur}
@anchor{im-gaussian-blur-channel}
@deffn Procedure im-gaussian-blur image sigma
@deffnx Procedure im-gaussian-blur-channel channel width height sigma
@cindex Gaussian blur
@cindex Gaussian smooth

Returns a new image or channel.

The new image or new channel is the result of the computation of the
Gaussian blurring, also known as the Gaussian smoothing, by means of a
convolution of @var{image} or @var{channel} with a 2D Gaussian function,
where @var{sigma} is the standard deviation of the Gaussian
distribution.
@end deffn


@anchor{im-gaussian-gradient}
@anchor{im-gaussian-gradient-channel}
@deffn Procedure im-gaussian-gradient image sigma
@deffnx Procedure im-gaussian-gradient-channel channel width height sigma
@cindex Gaussian gradient

Returns a new image or channel.

The new image or new channel is the result of the computation of the
strength of the first order partial derivatives by means of a
convolution of @var{image} or @var{channel} with the first order
derivative of a 2D Gaussian function, where @var{sigma} is the standard
deviation of the Gaussian distribution.
@end deffn
