@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


Guile-CV uses a series of support modules, each documented in the
following subsections. You may either import them all, like this
@code{(use-modules (cv support))}, or individually, such as
@code{(use-modules (cv support modules))}, @code{(use-modules (cv
support goops))}, ...


@menu
* Modules::
* Goops::
* G-export::
* Pi::
* Utils::
@end menu


@include api-support-modules.texi


@node Goops
@subsection Goops


@node G-export
@subsection G-export


@node Pi
@subsection Pi

@anchor{PI procedures}
@subheading Procedures

@ifhtml
@indentedblock
@table @code
@item @ref{radian->degree}
@item @ref{degree->radian}
@end table
@end indentedblock
@end ifhtml


@anchor{radian->degree}
@anchor{degree->radian}
@deffn Procedure radian->degree rad
@deffnx Procedure degree->radian deg

Returns respectively a degree or a radian value.
@end deffn


@anchor{PI variables}
@subheading Variables

@ifhtml
@indentedblock
@table @code
@item @ref{%pi}
@item @ref{%2pi}
@item @ref{%pi/2}
@end table
@end indentedblock
@end ifhtml


@anchor{%pi}
@anchor{%2pi}
@anchor{%pi/2}
@defvr Variable %pi
@defvrx Variable %2pi
@defvrx Variable %pi/2

Respectively bound to @code{(acos -1)}, @code{(* 2 %pi)} and
@code{(/ %pi 2)}.
@end defvr


@node Utils
@subsection Utils
