@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2017 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


@node API Reference
@chapter API Reference

@c Guile-CV Reference Manual still is a mock-up: any help is more
@c then welcome to improve this situation, thanks!


@menu
* API Overview::
* Guile-CV::
* Support::
@end menu


@node API Overview
@section API Overview

@include api-overview.texi


@node Guile-CV
@section Guile-CV

@include api-cv-idata.texi
@include api-cv-kdata.texi
@include api-cv-impex.texi
@include api-cv-imgproc.texi
@include api-cv-features.texi
@include api-cv-texture.texi
@include api-cv-filters.texi
@include api-cv-morphology.texi
@include api-cv-segmentation.texi
@include api-cv-utils.texi

@node Support
@section Support

@include api-support.texi
