@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU Guile-CV Reference Manual.
@c Copyright (C) 2016 - 2021 Free Software Foundation, Inc.
@c See the file guile-cv.texi for copying conditions.


@node Guile-CV Core Reference
@c @chapter Guile-CV Core Reference
@unnumbered III. Guile-CV Core Reference

@c Guile-CV Reference Manual still is a mock-up: any help is more
@c then welcome to improve this situation, thanks!


@menu
* Overview::
* Image Processing::
* Support::
@end menu


@node Overview
@section Overview

@include cr-ov.texi


@node Image Processing
@section Image Processing

@include cr-ip.texi


@node Support
@section Support

@include cr-support.texi
